import 'package:get/get.dart';

class Language extends Translations{
  @override

  Map <String, Map<String , String>> get keys => {
    'en':{
      'product':'Products',
      'category':'Categories',
      'seeall':'See all',
      'search':'Search for Products',
      'myproducts':'My Products',
      'addproduct':'Add Product',
      'name':'Name',
      'quantity':'Quantity',
      'price':'Price',
      'description':'Description',
      'upload':'Upload Image',
      'addfeedback':'Add a Feedback',
      'user':'User Name',
      'feedback': 'Feedback',
      'rating': 'Rating',
      'submit':'Submit',
      'language':'Choose a Language',
      'listfeedback':'List of Feedbacks',
      'D-Home':'H O M E',
      'D-Profile':'P R O F I L E',
      'D-MyProduct':'M Y P R O D U C T S',
      'D-Exchanges':'E X C H A N G E S',
      'D-Language':'S E L E C T  L A N G U A G E',
      'D-Messages':'M E S S A G E S',
      'D-logout':'L O G O U T',
      'producttype':'Product Type:',
      'normal':'Normal',
      'auction':'Auction',
      'scategory':'Category',
      'startingprice':'Starting Price',
      'timerm':'Timer (minutes)',
      'timers': 'Timer (seconds)',
      'messages':'Messages',
      'conError':'Error loading conversations',
      'conSuccess':'Start a conversation with a seller',
      'auctionp': 'Auction Products',
      'auctionon':'Ongoing Auctions',
      'myauction':'My Auctions',
      'stimer':'Start Timer',
      'D-Auction':'A U C T I O N S',
      'D-RecycleC':'R E C Y C  L E  C E N T E R',
      'D-RecycleP':'R E C Y C L E  P R O D U C T',
      'eproduct':'Edit Product',
      'cancel':'Cancel',
      'save':'Save',
      'dproduct':'Delete Product',
      'dconfirm':'Are you sure you want to delete this product?',
      'delete':'Delete',
      'unassigned':'Unassigned',
      'rproduct':'Recycle Product',
      'url':'Image URL',
      'acenter':'Assigned Center',
      'astatus':'Assigned Status',
      'recycle':'Recycle',
      'mproduct':'My Products',
      'pending':'Pending'

    },
    'sin':{
      'product':'නිෂ්පාදන',
      'category':'වර්ග',
      'seeall':'ඔක්කොම බලන්න',
      'search':'නිෂ්පාදන සඳහා සොයන්න',
      'myproducts':'මගේ නිෂ්පාදන',
      'addproduct':'නිෂ්පාදන එකතු කරන්න',
      'name':'නම',
      'quantity':'ප්‍රමාණය',
      'price':'මිල',
      'description':'විස්තර',
      'upload':'රූපය උඩුගත කරන්න',
      'addfeedback':'ප්‍රතිපෝෂණයක් එක් කරන්න',
      'user':'පරිශීලක නාමය',
      'feedback': 'ප්‍රතිපෝෂණ',
      'rating': 'ශ්‍රේණිගත කිරීම',
      'submit':'ඉදිරිපත් කරන්න',
      'language':'භාෂාවක් තෝරන්න',
      'listfeedback':'ප්‍රතිපෝෂණ ලැයිස්තුව',
      'D-Home':'මුල් පිටුව',
      'D-Profile':'පැතිකඩ',
      'D-MyProduct':'මගේ නිෂ්පාදන',
      'D-Exchanges':'හුවමාරු',
      'D-Language':'භාෂාවක් තෝරන්න',
      'D-Messages':'පණිවිඩ',
      'D-logout':'පිටවීම',
      'producttype':'නිෂ්පාදන වර්ගය:',
      'normal':'සාමාන්යයි',
      'auction':'වෙන්දේසිය',
      'scategory':'වර්ගය',
      'startingprice':'ආරම්භක මිල',
      'timerm':'ටයිමරය (මිනිත්තු)',
      'timers': 'ටයිමරය (තත්පර)',
      'messages':'පණිවිඩ',
      'conError':'සංවාද පූරණය කිරීමේ දෝෂයකි',
      'conSuccess':'විකුණුම්කරුවෙකු සමඟ සංවාදයක් ආරම්භ කරන්න',
      'auctionp': 'වෙන්දේසි නිෂ්පාදන',
      'auctionon':'දැනට පවතින වෙන්දේසි',
      'myauction':'මගේ වෙන්දේසි',
      'stimer':'ටයිමර් ආරම්භ කරන්න',
      'D-Auction':'වෙන්දේසි',
      'D-RecycleC':'ප්‍රතිචක්‍රීකරණ මධ්‍යස්ථානය',
      'D-RecycleP':'ප්‍රතිචක්‍රීකරණ නිෂ්පාදනය'
    }
  };
}